### ISSUE TITLE
S2GPS 03 - Práctica de TestRail

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/actividad-6-practica-de-calidad-de-testrail-con-wallet-entrevista-sistemhuerto#1]
[S2GPS 03 - Práctica de TestRail.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-calidad-de-testrail-con-wallet-entrevista-sistemhuerto/files/9677864/S2GPS.03.-.Practica.de.TestRail.pdf)

**Comment by Ferch0419** [comment]
Buen trabajo 20/20.

**Comment by josealfredo79** [comment]
Favor de realizar y complementar adecuadamente la practica

**Comment by josealfredo79** [comment]
@Ferch0419 favor de evaluar objetivamente...

**Comment by Yabin-2021** [comment]
Aquí anexo el reporte de práctica corregido:
[S2GPS 03 - Práctica de TestRail.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-calidad-de-testrail-con-wallet-entrevista-sistemhuerto/files/9707273/S2GPS.03.-.Practica.de.TestRail.pdf)

**Comment by Ferch0419** [comment]
18/20
Faltó describir la mayoría de las imágenes.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
